
title: Ron Dyck Resume
url: 'http://rondyck.gihub.io'
baseurl: '/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Ron Dyck
tagline: Full Stack Developer
pic: gravatar.jpeg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: rond@webbtech.net
# phone: 012 345 6789
website: webbtech.net #do not add http://
linkedin: https://ca.linkedin.com/in/pulpfree
github: pulpfree
twitter: '@pulpfree'

#Update all the sections by editing the files inside _includes folder.
